# Use the official OpenJDK image from the Docker Hub
FROM openjdk:17-jdk


# Expose the port that your Spring Boot application will run on
EXPOSE 9192

# Set the entry point to run the JAR file
ENTRYPOINT ["java", "-jar", "spring-boot-projeect.jar"]
