version: '3.9'

services:
  db:
    image: elfilaliimane02273/mysql:v1.0
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"]
      interval: 3s
      retries: 5
      start_period: 30s
    environment:
      MYSQL_DATABASE: 'my_database'
      MYSQL_ROOT_PASSWORD: 'mysql'
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
      - ./entrypoint.sh:/docker-entrypoint-initdb.d/entrypoint.sh
    networks:
      - pfa-ci-cd_spring-mysql

  backend:
    image: elfilaliimane02273/pfa-ci-cd-backend:v1.0
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "9192:9192"
    volumes:
      - ./spring-boot-projeect:/target
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/my_database
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: mysql
    networks:
      - pfa-ci-cd_spring-mysql
      - pfa-ci-cd_react-spring

  frontend:
    image: elfilaliimane02273/pfa-ci-cd-frontend:v1.0
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/sbr-stage:/app:rw
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - pfa-ci-cd_react-spring

volumes:
  mysql: {}

networks:
  pfa-ci-cd_react-spring: {}
  pfa-ci-cd_spring-mysql: {}

